<a href="https://colab.research.google.com/github/Prathamgupta19/Machine-learning-projects-/blob/main/ece_placemnets_stats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [4]:
data = pd.read_excel('/content/Copy of ECE Placemnets 2026 (1) (1).xlsx')

In [5]:
data.head()

,Dept Rank,Name,Roll no,Sno,CGPA upto 6th sem,Placement Status,Company,CTC,Unnamed: 8
0,209,AAKANKSHA KAUSHAL,2K22/EC/01,1.0,5.442,NaN,NaN,NaN,NaN
1,14,AAKARSH GUNJESH,2K22/EC/02,2.0,9.106,NaN,NaN,NaN,NaN
2,238,AAKASH NIGAM,2K22/EC/03,3.0,4.316,NaN,NaN,NaN,NaN
3,6,AAKSHAT JINDAL,2K22/EC/04,4.0,9.271,YES,Trusave Fintech (bachatt) 6M + FTE 2026,23.5,NaN
4,82,AARYAN MITTAL,2K22/EC/06,6.0,7.880,NaN,NaN,NaN,NaN

In [16]:
df = data[data['Placement Status '].isin(['YES', ' YES' , 'YES ' , ' YES '])]

In [17]:
df.head()

,Dept Rank,Name,Roll no,Sno,CGPA upto 6th sem,Placement Status,Company,CTC,Unnamed: 8
3,6,AAKSHAT JINDAL,2K22/EC/04,4.0,9.271,YES,Trusave Fintech (bachatt) 6M + FTE 2026,23.50,NaN
5,123,AASHIR REHMAN,2K22/EC/07,7.0,7.315,YES,ZS Associates 6M+FTE 2026 | BCN 6M+PPO 2026,14.15,15.68
11,1,ABHRONEEL MOITRA,2K22/EC/13,13.0,9.680,YES,Qualcomm 6M + FTE 2026,31.05,NaN
13,177,ADITYA,2K22/EC/15,15.0,6.237,YES,Futures First 6M + PPO 2026,17.00,NaN
20,21,ADVAITA SONI,2K22/EC/22,22.0,8.957,YES,Expedia,0.40,ppo

In [18]:
df.tail()

,Dept Rank,Name,Roll no,Sno,CGPA upto 6th sem,Placement Status,Company,CTC,Unnamed: 8
235,7,UDIT SINGH,2K22/EC/243,243.0,9.242,YES,Qualcomm 6M + FTE 2026,31.05,NaN
244,39,YANSHI SHARMA,2K22/EC/252,252.0,8.678,YES,Natwest Group,15.00,NaN
245,28,YASH ARORA,2K22/EC/253,253.0,8.862,YES,OYO BA 6M + PPO 2026,11.50,NaN
246,35,YASH KUMAR,2K22/EC/254,254.0,8.728,YES,Ciena 6M+PPO,14.00,NaN
247,12,YASH SHARMA,2K22/EC/255,255.0,9.124,YES,Qualcomm 6M + FTE 2026,31.05,NaN

In [19]:
df_ = df.CTC

In [21]:
df_.head()

3     23.50
5     14.15
11    31.05
13    17.00
20     0.40
Name: CTC, dtype: float64

In [22]:
df_.describe()

count    51.000000
mean     22.105686
std      10.694145
min       0.400000
25%      14.150000
50%      19.500000
75%      28.000000
max      57.000000
Name: CTC, dtype: float64